// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3puHCGyzIx94SRxBNCb9hjeL9FFSZuy8',
    appId: '1:302155767265:web:fd2b8f82563870b27146a0',
    messagingSenderId: '302155767265',
    projectId: 'chatting-e9ed1',
    authDomain: 'chatting-e9ed1.firebaseapp.com',
    storageBucket: 'chatting-e9ed1.appspot.com',
    measurementId: 'G-WVEMM48QY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChBN8JyZ2L7ZwqR0DczAamgctM4tWnWM',
    appId: '1:302155767265:android:2615a870cbd6ec497146a0',
    messagingSenderId: '302155767265',
    projectId: 'chatting-e9ed1',
    storageBucket: 'chatting-e9ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGNPUPxeeLuK3g1Nj4DP58aC_GgEdOd_g',
    appId: '1:302155767265:ios:31ffbf32f96759127146a0',
    messagingSenderId: '302155767265',
    projectId: 'chatting-e9ed1',
    storageBucket: 'chatting-e9ed1.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGNPUPxeeLuK3g1Nj4DP58aC_GgEdOd_g',
    appId: '1:302155767265:ios:e5a0a6fcff7a06e57146a0',
    messagingSenderId: '302155767265',
    projectId: 'chatting-e9ed1',
    storageBucket: 'chatting-e9ed1.appspot.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
